version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:latest

    working_directory: /go/src/github.com/shuheiktgw/go-lambda-linebot
    steps:
    - checkout

    - run: dep ensure
    - run: go test -v ./...